apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: react-nodejs-postgresql-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: react-nodejs-postgresql-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: react-nodejs-postgresql-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
