version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dos-devops
      POSTGRES_PASSWORD: dos-devops-pass
      POSTGRES_DB: dos-devops-db

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    links:
      - db
