apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: react-nodejs-postgresql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gundenaf/application-backend:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: react-nodejs-postgresql-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
